tasks:
  - name: Paperless-ng
    init: docker build --build-arg BUILD_FROM="homeassistant/amd64-base-debian:latest" -t local/paperless-ng ./paperless-ng/
    command: docker run -p 8000:8000 -v $PWD/paperless-ng/data:/data local/paperless-ng

ports:
  - port: 8000 # Paperless-ng
    onOpen: ignore

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - esbenp.prettier-vscode
