tasks:
  - name: Paperless-ngx
    init: docker build --build-arg BUILD_FROM="homeassistant/amd64-base-debian:latest" -t local/paperless-ngx ./paperless-ngx/
    command: docker run -p 8000:8000 -v $PWD/paperless-ngx/data:/data local/paperless-ngx

ports:
  - port: 8000 # Paperless-ngx
    onOpen: ignore

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - esbenp.prettier-vscode
